"""initialclear

Revision ID: 1f80b6c6f2e9
Revises: 25c8a4c398f9
Create Date: 2026-03-08 11:09:02.026768
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1f80b6c6f2e9'
down_revision: Union[str, None] = '25c8a4c398f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
