"""add admin fields and final schema updates

Revision ID: a205fe7eef29
Revises: b0638a178b74
Create Date: 2026-03-02 06:24:48.114235
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'a205fe7eef29'
down_revision: Union[str, None] = 'b0638a178b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
