"""add reviews notifications conversations messages tables

Revision ID: b0638a178b74
Revises: f88d375ec75a
Create Date: 2026-03-01 08:32:22.928126
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'b0638a178b74'
down_revision: Union[str, None] = 'f88d375ec75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escrows', sa.Column('freelancer_amount', sa.Float(), nullable=False))
    op.add_column('escrows', sa.Column('funding_transaction_id', sa.UUID(), nullable=True))
    op.add_column('escrows', sa.Column('release_transaction_id', sa.UUID(), nullable=True))
    op.alter_column('escrows', 'milestone_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('escrows', 'funded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_escrows_client_id', table_name='escrows')
    op.drop_index('ix_escrows_freelancer_id', table_name='escrows')
    op.drop_index('ix_escrows_milestone_id', table_name='escrows')
    op.drop_index('ix_escrows_stripe_payment_intent_id', table_name='escrows')
    op.create_unique_constraint('uq_escrow_milestone', 'escrows', ['milestone_id'])
    op.drop_constraint('escrows_milestone_id_fkey', 'escrows', type_='foreignkey')
    op.create_foreign_key(None, 'escrows', 'transactions', ['funding_transaction_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'escrows', 'transactions', ['release_transaction_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'escrows', 'milestones', ['milestone_id'], ['id'], ondelete='CASCADE')
    op.drop_column('escrows', 'refunded_at')
    op.drop_column('escrows', 'stripe_payment_intent_id')
    op.add_column('payment_accounts', sa.Column('provider', sa.Enum('STRIPE', 'WISE', 'MANUAL', name='paymentprovider'), nullable=False))
    op.add_column('payment_accounts', sa.Column('external_account_id', sa.String(length=255), nullable=True))
    op.add_column('payment_accounts', sa.Column('wise_email', sa.String(length=255), nullable=True))
    op.add_column('payment_accounts', sa.Column('wise_currency', sa.String(length=3), nullable=False))
    op.add_column('payment_accounts', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('payment_accounts', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.drop_index('ix_payment_accounts_status', table_name='payment_accounts')
    op.drop_index('ix_payment_accounts_stripe_account_id', table_name='payment_accounts')
    op.drop_index('ix_payment_accounts_stripe_customer_id', table_name='payment_accounts')
    op.drop_index('ix_payment_accounts_user_id', table_name='payment_accounts')
    op.create_index(op.f('ix_payment_accounts_user_id'), 'payment_accounts', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_provider', 'payment_accounts', ['user_id', 'provider'])
    op.drop_column('payment_accounts', 'available_balance')
    op.drop_column('payment_accounts', 'stripe_customer_id')
    op.drop_column('payment_accounts', 'payout_enabled')
    op.drop_column('payment_accounts', 'identity_verified')
    op.drop_column('payment_accounts', 'stripe_account_id')
    op.drop_column('payment_accounts', 'pending_balance')
    op.drop_column('payment_accounts', 'charges_enabled')
    op.add_column('transactions', sa.Column('transaction_type', sa.Enum('ESCROW_FUND', 'ESCROW_RELEASE', 'ESCROW_REFUND', 'PLATFORM_FEE', 'PAYOUT', name='transactiontype'), nullable=False))
    op.add_column('transactions', sa.Column('payer_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('payee_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('provider', sa.Enum('STRIPE', 'WISE', 'MANUAL', name='paymentprovider'), nullable=True))
    op.add_column('transactions', sa.Column('external_transaction_id', sa.String(length=255), nullable=True))
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_transactions_from_user_id', table_name='transactions')
    op.drop_index('ix_transactions_milestone_id', table_name='transactions')
    op.drop_index('ix_transactions_stripe_charge_id', table_name='transactions')
    op.drop_index('ix_transactions_stripe_payment_intent_id', table_name='transactions')
    op.drop_index('ix_transactions_stripe_transfer_id', table_name='transactions')
    op.drop_index('ix_transactions_to_user_id', table_name='transactions')
    op.drop_index('ix_transactions_type', table_name='transactions')
    op.drop_index('ix_transactions_type_status', table_name='transactions')
    op.create_index(op.f('ix_transactions_external_transaction_id'), 'transactions', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_payee_id'), 'transactions', ['payee_id'], unique=False)
    op.create_index(op.f('ix_transactions_payer_id'), 'transactions', ['payer_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.drop_constraint('transactions_to_user_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_from_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['payee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'users', ['payer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'stripe_transfer_id')
    op.drop_column('transactions', 'stripe_charge_id')
    op.drop_column('transactions', 'to_user_id')
    op.drop_column('transactions', 'from_user_id')
    op.drop_column('transactions', 'stripe_payment_intent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('from_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('to_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('stripe_charge_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('stripe_transfer_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('type', postgresql.ENUM('DEPOSIT', 'PAYMENT', 'RELEASE', 'WITHDRAWAL', 'REFUND', 'PLATFORM_FEE', 'DISPUTE_HOLD', name='transactiontype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_from_user_id_fkey', 'transactions', 'users', ['from_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('transactions_to_user_id_fkey', 'transactions', 'users', ['to_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payee_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_transaction_id'), table_name='transactions')
    op.create_index('ix_transactions_type_status', 'transactions', ['type', 'status'], unique=False)
    op.create_index('ix_transactions_type', 'transactions', ['type'], unique=False)
    op.create_index('ix_transactions_to_user_id', 'transactions', ['to_user_id'], unique=False)
    op.create_index('ix_transactions_stripe_transfer_id', 'transactions', ['stripe_transfer_id'], unique=True)
    op.create_index('ix_transactions_stripe_payment_intent_id', 'transactions', ['stripe_payment_intent_id'], unique=True)
    op.create_index('ix_transactions_stripe_charge_id', 'transactions', ['stripe_charge_id'], unique=False)
    op.create_index('ix_transactions_milestone_id', 'transactions', ['milestone_id'], unique=False)
    op.create_index('ix_transactions_from_user_id', 'transactions', ['from_user_id'], unique=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('transactions', 'external_transaction_id')
    op.drop_column('transactions', 'provider')
    op.drop_column('transactions', 'payee_id')
    op.drop_column('transactions', 'payer_id')
    op.drop_column('transactions', 'transaction_type')
    op.add_column('payment_accounts', sa.Column('charges_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('payment_accounts', sa.Column('pending_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('payment_accounts', sa.Column('stripe_account_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payment_accounts', sa.Column('identity_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('payment_accounts', sa.Column('payout_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('payment_accounts', sa.Column('stripe_customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payment_accounts', sa.Column('available_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_provider', 'payment_accounts', type_='unique')
    op.drop_index(op.f('ix_payment_accounts_user_id'), table_name='payment_accounts')
    op.create_index('ix_payment_accounts_user_id', 'payment_accounts', ['user_id'], unique=True)
    op.create_index('ix_payment_accounts_stripe_customer_id', 'payment_accounts', ['stripe_customer_id'], unique=True)
    op.create_index('ix_payment_accounts_stripe_account_id', 'payment_accounts', ['stripe_account_id'], unique=True)
    op.create_index('ix_payment_accounts_status', 'payment_accounts', ['status'], unique=False)
    op.drop_column('payment_accounts', 'is_default')
    op.drop_column('payment_accounts', 'metadata_json')
    op.drop_column('payment_accounts', 'wise_currency')
    op.drop_column('payment_accounts', 'wise_email')
    op.drop_column('payment_accounts', 'external_account_id')
    op.drop_column('payment_accounts', 'provider')
    op.add_column('escrows', sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('escrows', sa.Column('refunded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'escrows', type_='foreignkey')
    op.drop_constraint(None, 'escrows', type_='foreignkey')
    op.drop_constraint(None, 'escrows', type_='foreignkey')
    op.create_foreign_key('escrows_milestone_id_fkey', 'escrows', 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_escrow_milestone', 'escrows', type_='unique')
    op.create_index('ix_escrows_stripe_payment_intent_id', 'escrows', ['stripe_payment_intent_id'], unique=True)
    op.create_index('ix_escrows_milestone_id', 'escrows', ['milestone_id'], unique=True)
    op.create_index('ix_escrows_freelancer_id', 'escrows', ['freelancer_id'], unique=False)
    op.create_index('ix_escrows_client_id', 'escrows', ['client_id'], unique=False)
    op.alter_column('escrows', 'funded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('escrows', 'milestone_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('escrows', 'release_transaction_id')
    op.drop_column('escrows', 'funding_transaction_id')
    op.drop_column('escrows', 'freelancer_amount')
    # ### end Alembic commands ###
